title: Sachidanand Chaudhary
author: GitHub User
email:Sachidanand951@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning to host pages on Github. :smile:
# social links
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
